### ISSUE TITLE
Document how to reload the XPC service

### ISSUE THREAD

**Issue by mjpieters** [macgpg/libmacgpg-free#1]
After installing the free `org.gpgtools.Libmacgpg` binary, the `org.gpgtools.Libmacgpg.xpc` service must be restarted if running.

I couldn't be bothered with learning the right magic incantations for this one; I closed Mail, and used an app called LaunchControl to find the service in the global agents list, then stop and start the service.

Without this step, the old paywalled version is still going to be active and nag you when using Mail.

**Comment by jonasschnelli** [comment]
Yes. This seems to be possible...
I'll add a note and a restart command to the readme.

Thanks for the report.

**Comment by dhowe** [comment]
this is indeed required...
```
$ sudo launchctl stop org.gpgtools.Libmacgpg.xpc
$ sudo launchctl start org.gpgtools.Libmacgpg.xpc
```

**Comment by nathanvy** [comment]
It is enough to close Mail.app and then kill the org.gpgtools.Libmacgpg.xpc process. 

`➜  ~ ps aux | grep gpg
nathan            6197   0.0  0.0  4372988   4996   ??  S    23Sep18   0:19.93 /Library/Application Support/GPGTools/org.gpgtools.Libmacgpg.xpc/Contents/MacOS/org.gpgtools.Libmacgpg`

Sorry for the long lines.  You can see the process ID is 6197.  You just have to kill it, then:

`➜  ~ kill 6197`

**Comment by jonasschnelli** [comment]
I think we can close this...
please open a PR if the readme is not precise enough
