### ISSUE TITLE
Any way to build this without install xcode ?

### ISSUE THREAD

**Issue by dhowe** [macgpg/libmacgpg-free#2]
I have command-line tools installed but not the massively bloated xcode, and I when I run 'make', I get the following:
`
code-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

Would be great if we could build this without xcode

**Comment by jonasschnelli** [comment]
I think this would be a rather complex project and the intention is not to change the build system and make the replacement incompatible with the upstream library.

**Comment by napaxton** [comment]
What about if one has the XCode CL tools but not full XCode? Is there an alternate to the conventional "make" command to not need to invoke the full XCode?

**Comment by jonasschnelli** [comment]
> What about if one has the XCode CL tools but not full Xcode?

I don't think this could be supported.
