### ISSUE TITLE
Please add support for GPG Suite 2019.1b1

### ISSUE THREAD

**Issue by marcopeereboom** [macgpg/libmacgpg-free#3]
GPG Suite 2019.1b1 is out and it would be nice to have an update.

**Comment by jonasschnelli** [comment]
I guess they haven't release the source code yet? Have they? It may even be a violation of the license to ship binaries with no option to download the sources.

**Comment by step21** [comment]
When I go to the page, both binaries an source show 2018.5. Maybe they only show 2019 for Mojave? When I enter the url manually it works https://releases.gpgtools.org/GPG_Suite-2019.1b1.txz

**Comment by timbru31** [comment]
[org.gpgtools.Libmacgpg.zip](https://github.com/macgpg/libmacgpg-free/files/3376460/org.gpgtools.Libmacgpg.zip)
This is the patched `org.gpgtools.Libmacgpg` from the GPG_Suite-2019.1b1.txz file. (untested, I'm still on 2018.5)

**Comment by napaxton** [comment]
This works nicely.

My process:
* Kill the org.gpgtools.Libmacgpg.xpc process (terminal or Activity Monitor)
* Copy the mod’d libmacgpg (following assumes you are in the dir where the mod’d Libmacgpg is: sudo cp org.gpgtools.Libmacgpg /Library/Application\ Support/GPGTools/org.gpgtools.Libmacgpg.xpc/Contents/MacOS
* sudo chmod 755 /Library/Application\ Support/GPGTools/org.gpgtools.Libmacgpg.xpc/Contents/MacOS/org.gpgtools.Libmacgpg
* Then restart: open mail, invoke terminal, however you like.

**Comment by JayBrown** [comment]
Final 2019.1 has been released. Does the above patched version from the beta still work?

**Comment by timbru31** [comment]
I assume no, since there is one new commit to the `Source/org.gpgtools.Libmacgpg.xpc/JailfreeTask.m` file since April 2019: https://github.com/GPGTools/Libmacgpg/commit/0cd8488c57efd2081c68f0526d280dc583ea235d#diff-233ee2493267419d397939a53add6900

I've patched the source code of 2019.1 (final):

[org.gpgtools.Libmacgpg.zip](https://github.com/macgpg/libmacgpg-free/files/3532264/org.gpgtools.Libmacgpg.zip)

**Comment by jonasschnelli** [comment]
I just added support for the 2019.1 release.
Closing.

**Comment by napaxton** [comment]
Just to confirm, I’ve got this working as well. I know this is closed, but wanted to confirm.
-----
Nathan Paxton


Outside of a dog, a book is man's best friend. Inside of a dog, it's too dark to read.
	—Mark Twain
(It's kind of cramped, too.)
