### ISSUE TITLE
[INFO] 2019.2 released

### ISSUE THREAD

**Issue by JayBrown** [macgpg/libmacgpg-free#5]
Released on 15 Nov 2019:
https://gpgtools.org/releases/gpgsuite/2019.2/release-notes.html

Does the 2019.1 release work, or do we need a new one?

**Comment by jonasschnelli** [comment]
Thanks for the info.
I'll take a look at the new release asap.

**Comment by matis-schotte** [comment]
Seems like there is a new 'GMSupportPlan' module which they don't publish on github. But still the paddle logic relies in the xpc. Didn't look too deep since I'm on trial now ... 

Also I was actually wondering why replacing the xpc macos executable just works/worked, is (or was) the signature not verified?
Would it also be possible to to replace the mail plugin or would it break because of the missing signature?

**Comment by sylvarg** [comment]
@jonasschnelli Any update on this?

**Comment by JayBrown** [comment]
@matis-schotte the executable is unsigned, so the whole xpc is treated as unsigned, and seems to work fine, at least on Mojave, even if there's still a residual `CodeResources` file from the previous code-signing. Though you might want to remove any quarantine from the xpc, just to be sure & circumvent Gatekeeper checks: `sudo xattr -dr com.apple.quarantine /Library/Application\ Support/GPGTools/org.gpgtools.Libmacgpg.xpc` … as for Mail plugins, I have one unsigned plugin running smoothly on Mojave, so an unsigned GPGMail plugin should also work fine imho.

**Comment by fl4co** [comment]
Any ETA yet?

**Comment by delreluca** [comment]
I wanted to point out that the source that has been missing so far has been now published, see the issue on the competing project https://github.com/GpgMailNoActivation/GpgMailNoActivation/issues/4

**Comment by Tyzlor** [comment]
Hi

Thought I would check and see if this project is still active and if there is a release for 2019.2 coming out anytime..

**Comment by JayBrown** [comment]
I just upgraded to Catalina, tried using the alternate 2019.2 release by a well-known cracking group, but that release is buggy… doesn't work…

**Comment by JayBrown** [comment]
New version 2020.1 released; see here: https://github.com/macgpg/libmacgpg-free/issues/8

Closing this topic.
